"use client";

import { useState } from "react";
import { motion } from "framer-motion";
import { Header } from "@/components/layout/Header";
import { GlassCard } from "@/components/ui/GlassCard";
import { useQuery } from "@tanstack/react-query";
import { 
  getOverview, 
  getDemographics, 
  getConcerns, 
  getQuality,
  getKeyFindings,
  getRecommendations,
  getDecisionSummary
} from "@/lib/api";
import {
  Download,
  FileText,
  FileSpreadsheet,
  CheckCircle,
  Loader2,
  Presentation,
  Shield,
} from "lucide-react";

export default function ExportPage() {
  const [downloadingCSV, setDownloadingCSV] = useState(false);
  const [downloadingSummary, setDownloadingSummary] = useState(false);
  const [downloadingReport, setDownloadingReport] = useState(false);
  const [downloadingCommittee, setDownloadingCommittee] = useState(false);
  const [successMessage, setSuccessMessage] = useState<string | null>(null);

  // Fetch all data for export
  const { data: overview } = useQuery({ queryKey: ["overview"], queryFn: getOverview });
  const { data: demographics } = useQuery({ queryKey: ["demographics", "course"], queryFn: () => getDemographics("course") });
  const { data: concerns } = useQuery({ queryKey: ["concerns"], queryFn: () => getConcerns() });
  const { data: quality } = useQuery({ queryKey: ["quality"], queryFn: getQuality });
  const { data: decisionSummary } = useQuery({ queryKey: ["decision-summary"], queryFn: getDecisionSummary });

  const showSuccess = (message: string) => {
    setSuccessMessage(message);
    setTimeout(() => setSuccessMessage(null), 3000);
  };

  const downloadCSV = async () => {
    setDownloadingCSV(true);
    try {
      const response = await fetch("http://localhost:8000/api/data/responses");
      const data = await response.json();
      
      if (data && data.length > 0) {
        const headers = Object.keys(data[0]);
        const csvContent = [
          headers.join(","),
          ...data.map((row: Record<string, unknown>) =>
            headers.map((h) => {
              const val = row[h];
              if (typeof val === "string" && (val.includes(",") || val.includes("\n"))) {
                return `"${val.replace(/"/g, '""')}"`;
              }
              return val ?? "";
            }).join(",")
          ),
        ].join("\n");

        const blob = new Blob([csvContent], { type: "text/csv;charset=utf-8;" });
        const url = URL.createObjectURL(blob);
        const link = document.createElement("a");
        link.href = url;
        link.download = `survey_responses_${new Date().toISOString().split("T")[0]}.csv`;
        link.click();
        URL.revokeObjectURL(url);
        
        showSuccess("CSV file downloaded successfully!");
      }
    } catch (error) {
      console.error("Failed to download CSV:", error);
      alert("Failed to download CSV. Please ensure the backend is running.");
    } finally {
      setDownloadingCSV(false);
    }
  };

  const downloadExecutiveSummary = async () => {
    setDownloadingSummary(true);
    try {
      if (!overview) {
        alert("Please wait for data to load.");
        return;
      }

      const summary = `
CAMPUS ENTRY NOTIFICATION SURVEY
================================
EXECUTIVE SUMMARY
Generated: ${new Date().toLocaleString()}

OVERVIEW
--------
Total Responses: ${overview.total_responses}
Valid Responses: ${overview.valid_responses}
Flagged Responses: ${overview.flagged_responses}

QUESTION 1: PARENT NOTIFICATION SYSTEM
--------------------------------------
Support: ${overview.q1_support_count} (${overview.q1_support_percent}%)
Oppose: ${overview.q1_oppose_count} (${(100 - overview.q1_support_percent).toFixed(1)}%)

QUESTION 2: 24/7 ENTRY/EXIT MONITORING
--------------------------------------
Support: ${overview.q2_support_count} (${overview.q2_support_percent}%)
Oppose: ${overview.q2_oppose_count} (${(100 - overview.q2_support_percent).toFixed(1)}%)

TOP CONCERNS
------------
${concerns ? concerns.slice(0, 5).map((c, i) => 
  `${i + 1}. ${c.concern_name}: ${c.count} mentions (${c.percentage}%)`
).join("\n") : "No concerns data available"}

---
Generated by Campus Entry Notification Survey Dashboard
      `.trim();

      const blob = new Blob([summary], { type: "text/plain;charset=utf-8;" });
      const url = URL.createObjectURL(blob);
      const link = document.createElement("a");
      link.href = url;
      link.download = `executive_summary_${new Date().toISOString().split("T")[0]}.txt`;
      link.click();
      URL.revokeObjectURL(url);
      
      showSuccess("Executive summary downloaded!");
    } catch (error) {
      console.error("Failed to generate summary:", error);
      alert("Failed to generate summary.");
    } finally {
      setDownloadingSummary(false);
    }
  };

  const downloadDetailedReport = async () => {
    setDownloadingReport(true);
    try {
      if (!overview) {
        alert("Please wait for data to load.");
        return;
      }

      const htmlReport = `
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Survey Analysis Report</title>
  <style>
    body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; margin: 40px; line-height: 1.6; color: #1a1a1a; }
    h1 { color: #1e3a5f; border-bottom: 2px solid #1e3a5f; padding-bottom: 10px; }
    h2 { color: #2d5a87; margin-top: 30px; }
    .metric { display: inline-block; background: #f0f4f8; padding: 15px 25px; margin: 10px; border-radius: 8px; text-align: center; }
    .metric-value { font-size: 28px; font-weight: bold; color: #1e3a5f; }
    .metric-label { font-size: 12px; color: #666; text-transform: uppercase; }
    table { width: 100%; border-collapse: collapse; margin: 20px 0; }
    th, td { padding: 12px; text-align: left; border-bottom: 1px solid #ddd; }
    th { background: #f0f4f8; font-weight: 600; }
    .support { color: #059669; }
    .oppose { color: #dc2626; }
    .footer { margin-top: 40px; padding-top: 20px; border-top: 1px solid #ddd; color: #666; font-size: 12px; }
    @media print { body { margin: 20px; } }
  </style>
</head>
<body>
  <h1>Campus Entry Notification Survey</h1>
  <p><strong>Detailed Analysis Report</strong> | Generated: ${new Date().toLocaleString()}</p>
  
  <h2>Response Overview</h2>
  <div>
    <div class="metric">
      <div class="metric-value">${overview.total_responses}</div>
      <div class="metric-label">Total Responses</div>
    </div>
    <div class="metric">
      <div class="metric-value">${overview.valid_responses}</div>
      <div class="metric-label">Valid Responses</div>
    </div>
  </div>
  
  <h2>Question 1: Parent Notification System</h2>
  <table>
    <tr><th>Response</th><th>Count</th><th>Percentage</th></tr>
    <tr><td class="support">Support</td><td>${overview.q1_support_count}</td><td>${overview.q1_support_percent}%</td></tr>
    <tr><td class="oppose">Oppose</td><td>${overview.q1_oppose_count}</td><td>${(100 - overview.q1_support_percent).toFixed(1)}%</td></tr>
  </table>
  
  <h2>Question 2: 24/7 Monitoring</h2>
  <table>
    <tr><th>Response</th><th>Count</th><th>Percentage</th></tr>
    <tr><td class="support">Support</td><td>${overview.q2_support_count}</td><td>${overview.q2_support_percent}%</td></tr>
    <tr><td class="oppose">Oppose</td><td>${overview.q2_oppose_count}</td><td>${(100 - overview.q2_support_percent).toFixed(1)}%</td></tr>
  </table>
  
  ${demographics ? `
  <h2>Demographics Breakdown</h2>
  <table>
    <tr><th>Category</th><th>Total</th><th>Q1 Support</th><th>Q2 Support</th></tr>
    ${demographics.map(d => `
    <tr><td>${d.category}</td><td>${d.total}</td><td>${d.q1_yes_percent}%</td><td>${d.q2_yes_percent}%</td></tr>
    `).join("")}
  </table>
  ` : ""}
  
  ${concerns ? `
  <h2>Top Concerns</h2>
  <table>
    <tr><th>Concern</th><th>Mentions</th><th>Percentage</th></tr>
    ${concerns.slice(0, 10).map(c => `
    <tr><td>${c.concern_name}</td><td>${c.count}</td><td>${c.percentage}%</td></tr>
    `).join("")}
  </table>
  ` : ""}
  
  <div class="footer">
    <p>Generated by Campus Entry Notification Survey Dashboard</p>
  </div>
</body>
</html>
      `.trim();

      const blob = new Blob([htmlReport], { type: "text/html;charset=utf-8;" });
      const url = URL.createObjectURL(blob);
      const link = document.createElement("a");
      link.href = url;
      link.download = `detailed_report_${new Date().toISOString().split("T")[0]}.html`;
      link.click();
      URL.revokeObjectURL(url);
      
      showSuccess("Detailed report downloaded!");
    } catch (error) {
      console.error("Failed to generate report:", error);
      alert("Failed to generate report.");
    } finally {
      setDownloadingReport(false);
    }
  };

  const downloadCommitteeReport = async () => {
    setDownloadingCommittee(true);
    try {
      if (!decisionSummary) {
        alert("Please wait for data to load.");
        return;
      }

      const findings = decisionSummary.findings.findings;
      const recommendations = decisionSummary.recommendations.recommendations;
      const metrics = decisionSummary.metrics;

      const htmlReport = `
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Committee Report - Campus Entry Survey</title>
  <style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body { font-family: 'Georgia', serif; margin: 0; line-height: 1.8; color: #1a1a2e; background: white; }
    .cover { height: 100vh; display: flex; flex-direction: column; justify-content: center; align-items: center; background: linear-gradient(135deg, #1e3a5f 0%, #2d5a87 100%); color: white; text-align: center; page-break-after: always; }
    .cover h1 { font-size: 2.5rem; margin-bottom: 1rem; font-weight: normal; }
    .cover .subtitle { font-size: 1.2rem; opacity: 0.9; }
    .cover .date { margin-top: 3rem; opacity: 0.7; }
    .cover .institution { margin-top: 1rem; font-style: italic; }
    .content { max-width: 800px; margin: 0 auto; padding: 40px; }
    h2 { color: #1e3a5f; font-size: 1.5rem; margin: 2rem 0 1rem; padding-bottom: 0.5rem; border-bottom: 2px solid #1e3a5f; }
    h3 { color: #2d5a87; font-size: 1.2rem; margin: 1.5rem 0 0.5rem; }
    .executive-summary { background: #f8fafc; padding: 1.5rem; border-left: 4px solid #1e3a5f; margin: 1.5rem 0; }
    .metric-grid { display: grid; grid-template-columns: repeat(2, 1fr); gap: 1rem; margin: 1.5rem 0; }
    .metric-box { background: #f8fafc; padding: 1.5rem; border-radius: 8px; text-align: center; }
    .metric-value { font-size: 2.5rem; font-weight: bold; color: #1e3a5f; }
    .metric-label { font-size: 0.875rem; color: #64748b; margin-top: 0.25rem; }
    .metric-ci { font-size: 0.75rem; color: #94a3b8; margin-top: 0.5rem; }
    .finding { padding: 1rem; margin: 0.75rem 0; background: #f8fafc; border-radius: 8px; }
    .finding-text { font-weight: 500; color: #1e3a5f; }
    .finding-stat { font-size: 0.875rem; color: #64748b; margin-top: 0.25rem; }
    .badge { display: inline-block; padding: 0.25rem 0.75rem; border-radius: 999px; font-size: 0.75rem; font-weight: 500; margin-left: 0.5rem; }
    .badge-high { background: #fee2e2; color: #dc2626; }
    .badge-medium { background: #fef3c7; color: #d97706; }
    .badge-low { background: #dbeafe; color: #2563eb; }
    .recommendation { padding: 1.25rem; margin: 1rem 0; border-radius: 8px; border-left: 4px solid; }
    .recommendation.high { background: #fef2f2; border-color: #dc2626; }
    .recommendation.medium { background: #fffbeb; border-color: #d97706; }
    .recommendation.low { background: #eff6ff; border-color: #2563eb; }
    .recommendation h4 { font-size: 1rem; margin-bottom: 0.5rem; }
    .recommendation p { font-size: 0.9rem; color: #475569; }
    .recommendation .justification { font-size: 0.8rem; color: #64748b; font-style: italic; margin-top: 0.75rem; }
    .action-items { margin-top: 0.75rem; padding-left: 1.25rem; }
    .action-items li { font-size: 0.875rem; color: #475569; margin: 0.25rem 0; }
    .concerns-list { display: grid; grid-template-columns: repeat(2, 1fr); gap: 0.75rem; margin: 1rem 0; }
    .concern-item { display: flex; align-items: center; gap: 0.5rem; padding: 0.75rem; background: #f8fafc; border-radius: 6px; }
    .concern-dot { width: 12px; height: 12px; border-radius: 50%; }
    .concern-name { flex: 1; font-weight: 500; }
    .concern-count { color: #64748b; font-size: 0.875rem; }
    .methodology { background: #f8fafc; padding: 1.5rem; border-radius: 8px; margin: 2rem 0; }
    .methodology h3 { margin-top: 0; }
    .methodology ul { padding-left: 1.5rem; }
    .methodology li { margin: 0.5rem 0; color: #475569; }
    .footer { text-align: center; padding: 2rem; color: #64748b; font-size: 0.875rem; border-top: 1px solid #e2e8f0; margin-top: 3rem; }
    @media print { 
      .cover { height: 100vh; } 
      .content { padding: 20px; }
      .recommendation, .finding { break-inside: avoid; }
    }
  </style>
</head>
<body>
  <div class="cover">
    <h1>Campus Entry Notification Survey</h1>
    <p class="subtitle">Committee Report & Policy Recommendations</p>
    <p class="date">Generated: ${new Date().toLocaleDateString('en-US', { weekday: 'long', year: 'numeric', month: 'long', day: 'numeric' })}</p>
    <p class="institution">IIT Kharagpur</p>
  </div>
  
  <div class="content">
    <h2>Executive Summary</h2>
    <div class="executive-summary">
      <p>${decisionSummary.findings.executive_summary}</p>
    </div>
    
    <h2>Key Metrics</h2>
    <div class="metric-grid">
      <div class="metric-box">
        <div class="metric-value">${metrics.total_responses.toLocaleString()}</div>
        <div class="metric-label">Total Responses</div>
        <div class="metric-ci">Sample: ${metrics.sample_adequacy.adequacy}</div>
      </div>
      <div class="metric-box">
        <div class="metric-value">${(100 - metrics.q1_support.percentage).toFixed(1)}%</div>
        <div class="metric-label">Oppose Q1 (Notification)</div>
        <div class="metric-ci">95% CI: ${(100 - metrics.q1_support.ci_upper).toFixed(1)}% - ${(100 - metrics.q1_support.ci_lower).toFixed(1)}%</div>
      </div>
      <div class="metric-box">
        <div class="metric-value">${(100 - metrics.q2_support.percentage).toFixed(1)}%</div>
        <div class="metric-label">Oppose Q2 (Monitoring)</div>
        <div class="metric-ci">95% CI: ${(100 - metrics.q2_support.ci_upper).toFixed(1)}% - ${(100 - metrics.q2_support.ci_lower).toFixed(1)}%</div>
      </div>
      <div class="metric-box">
        <div class="metric-value">±${metrics.sample_adequacy.worst_case_moe_percent}%</div>
        <div class="metric-label">Margin of Error</div>
        <div class="metric-ci">At 95% confidence level</div>
      </div>
    </div>
    
    <h2>Key Findings</h2>
    ${findings.slice(0, 7).map((f: any, i: number) => `
    <div class="finding">
      <span class="finding-text">${i + 1}. ${f.text}</span>
      <span class="badge badge-${f.confidence === 'high' ? 'low' : f.confidence === 'medium' ? 'medium' : 'high'}">${f.confidence} confidence</span>
      ${f.supporting_stat ? `<div class="finding-stat">${f.supporting_stat}</div>` : ''}
    </div>
    `).join('')}
    
    <h2>Top Concerns Raised</h2>
    <div class="concerns-list">
      ${decisionSummary.concerns_summary.map((c: any) => `
      <div class="concern-item">
        <div class="concern-dot" style="background-color: ${c.color}"></div>
        <span class="concern-name">${c.concern_name}</span>
        <span class="concern-count">${c.count}</span>
      </div>
      `).join('')}
    </div>
    
    <h2>Policy Recommendations</h2>
    <p style="color: #475569; margin-bottom: 1rem;">${decisionSummary.recommendations.summary}</p>
    
    ${recommendations.map((r: any) => `
    <div class="recommendation ${r.priority}">
      <h4>${r.title} <span class="badge badge-${r.priority}">${r.priority} priority</span></h4>
      <p>${r.description}</p>
      <p class="justification"><strong>Based on:</strong> ${r.justification}</p>
      <ul class="action-items">
        ${r.action_items.map((item: string) => `<li>${item}</li>`).join('')}
      </ul>
    </div>
    `).join('')}
    
    <div class="methodology">
      <h3>Methodology Note</h3>
      <ul>
        <li><strong>Sample Size:</strong> ${metrics.total_responses.toLocaleString()} survey responses collected</li>
        <li><strong>Valid Responses:</strong> ${metrics.valid_responses.toLocaleString()} responses passed quality checks</li>
        <li><strong>Statistical Confidence:</strong> 95% confidence intervals reported for all percentages</li>
        <li><strong>Sample Adequacy:</strong> ${metrics.sample_adequacy.note}</li>
        <li><strong>Analysis Methods:</strong> Descriptive statistics, chi-square tests, and NLP-based content analysis</li>
      </ul>
    </div>
    
    <div class="footer">
      <p>This report was automatically generated by the Campus Entry Notification Survey Dashboard</p>
      <p>For questions or additional analysis, contact the survey administrator</p>
    </div>
  </div>
</body>
</html>
      `.trim();

      const blob = new Blob([htmlReport], { type: "text/html;charset=utf-8;" });
      const url = URL.createObjectURL(blob);
      const link = document.createElement("a");
      link.href = url;
      link.download = `committee_report_${new Date().toISOString().split("T")[0]}.html`;
      link.click();
      URL.revokeObjectURL(url);
      
      showSuccess("Committee report downloaded! Open in browser and print to PDF.");
    } catch (error) {
      console.error("Failed to generate committee report:", error);
      alert("Failed to generate committee report.");
    } finally {
      setDownloadingCommittee(false);
    }
  };

  const exportOptions = [
    {
      title: "Committee Report",
      description: "Professional report with key findings, recommendations, and statistical confidence intervals. Ready for committee presentation.",
      icon: Presentation,
      color: "amber",
      action: downloadCommitteeReport,
      loading: downloadingCommittee,
      featured: true,
    },
    {
      title: "Full Data CSV",
      description: "Export all survey responses as a CSV file for use in Excel, Google Sheets, or other data tools.",
      icon: FileSpreadsheet,
      color: "emerald",
      action: downloadCSV,
      loading: downloadingCSV,
    },
    {
      title: "Executive Summary",
      description: "A concise text summary of key findings, metrics, and insights suitable for quick sharing.",
      icon: FileText,
      color: "blue",
      action: downloadExecutiveSummary,
      loading: downloadingSummary,
    },
    {
      title: "Detailed Report",
      description: "Comprehensive HTML report with all analytics. Open in browser and print to PDF.",
      icon: FileText,
      color: "purple",
      action: downloadDetailedReport,
      loading: downloadingReport,
    },
  ];

  const colorStyles: Record<string, { bg: string; border: string; icon: string }> = {
    amber: { bg: "bg-amber-400/10", border: "border-amber-400/20", icon: "text-amber-400" },
    emerald: { bg: "bg-emerald-400/10", border: "border-emerald-400/20", icon: "text-emerald-400" },
    blue: { bg: "bg-blue-400/10", border: "border-blue-400/20", icon: "text-blue-400" },
    purple: { bg: "bg-purple-400/10", border: "border-purple-400/20", icon: "text-purple-400" },
  };

  return (
    <div className="max-w-4xl mx-auto">
      <Header
        title="Export Center"
        subtitle="Download reports and data for presentations"
      />

      {/* Success Toast */}
      {successMessage && (
        <motion.div
          initial={{ opacity: 0, y: -20 }}
          animate={{ opacity: 1, y: 0 }}
          exit={{ opacity: 0 }}
          className="fixed top-20 right-4 bg-emerald-500/90 text-white px-4 py-3 rounded-lg shadow-lg flex items-center gap-2 z-50"
        >
          <CheckCircle className="w-5 h-5" />
          {successMessage}
        </motion.div>
      )}

      {/* Export Options */}
      <div className="space-y-4">
        {exportOptions.map((option, index) => {
          const styles = colorStyles[option.color];
          return (
            <motion.div
              key={option.title}
              initial={{ opacity: 0, y: 10 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ delay: index * 0.1 }}
            >
              <GlassCard className={`p-6 ${option.featured ? 'ring-2 ring-amber-400/30' : ''}`}>
                {option.featured && (
                  <div className="flex items-center gap-2 mb-3">
                    <Shield className="w-4 h-4 text-amber-400" />
                    <span className="text-xs font-medium text-amber-400 uppercase tracking-wide">Recommended for Committees</span>
                  </div>
                )}
                <div className="flex items-start justify-between">
                  <div className="flex items-start gap-4">
                    <div className={`p-3 rounded-lg ${styles.bg} ${styles.border} border`}>
                      <option.icon className={`w-6 h-6 ${styles.icon}`} />
                    </div>
                    <div>
                      <h3 className="text-lg font-semibold text-white">{option.title}</h3>
                      <p className="text-white/50 text-sm mt-1 max-w-md">{option.description}</p>
                    </div>
                  </div>
                  
                  <button
                    onClick={option.action}
                    disabled={option.loading}
                    className={`flex items-center gap-2 px-5 py-2.5 rounded-lg font-medium text-sm transition-all ${
                      option.loading
                        ? "bg-white/10 text-white/50 cursor-not-allowed"
                        : `${styles.bg} ${styles.border} border ${styles.icon} hover:bg-opacity-20`
                    }`}
                  >
                    {option.loading ? (
                      <Loader2 className="w-4 h-4 animate-spin" />
                    ) : (
                      <Download className="w-4 h-4" />
                    )}
                    {option.loading ? "Generating..." : "Download"}
                  </button>
                </div>
              </GlassCard>
            </motion.div>
          );
        })}
      </div>

      {/* Tips */}
      <GlassCard className="p-6 mt-6">
        <h3 className="text-base font-semibold text-white mb-3">Tips</h3>
        <ul className="space-y-2 text-sm text-white/60">
          <li className="flex items-start gap-2">
            <span className="text-amber-400 mt-1">*</span>
            <strong className="text-white/80">Committee Report</strong> includes confidence intervals, findings, and recommendations - ideal for formal presentations.
          </li>
          <li className="flex items-start gap-2">
            <span className="text-emerald-400 mt-1">*</span>
            CSV files can be opened directly in Excel or Google Sheets for custom analysis.
          </li>
          <li className="flex items-start gap-2">
            <span className="text-blue-400 mt-1">*</span>
            Open HTML reports in a browser and use Ctrl/Cmd+P to print or save as PDF.
          </li>
        </ul>
      </GlassCard>
    </div>
  );
}
